#lista de tuplas con las producciones (nombre y produccion)
producciones = [
    ("program", "declarationlist"),
    ("declarationlist", "declaration { DATA_TYPE_KEY FUNCTION_TYPE_KEY }"),
    ("declaration", "vardeclaration | fundeclaration"),
    ("vardeclaration", "typespecifier IDENTIFIER [ ASSIGNMENT_OPERATOR expression ] PUNCTUATION_OPERATOR | typespecifier IDENTIFIER PUNCTUATION_OPERATOR NUMBER PUNCTUATION_OPERATOR PUNCTUATION_OPERATOR"),
    ("typespecifier", "DATA_TYPE_KEY | FUNCTION_TYPE_KEY"),
    ("fundeclaration", "typespecifier IDENTIFIER PUNCTUATION_OPERATOR params PUNCTUATION_OPERATOR compoundstmt"),
    ("params", "paramlist | FUNCTION_TYPE_KEY"),
    ("paramlist", "param {PUNCTUATION_OPERATOR param}"),
    ("param", "typespecifier IDENTIFIER | typespecifier IDENTIFIER PUNCTUATION_OPERATOR PUNCTUATION_OPERATOR"),
    ("compoundstmt", "PUNCTUATION_OPERATOR localdeclarations statementlist PUNCTUATION_OPERATOR"),
    ("localdeclarations", "{DATA_TYPE_KEY  FUNCTION_TYPE_KEY}"),
    ("statementlist", "{IDENTIFIER NUMBER { CONTROL_TYPE_KEY FUNCTION_TYPE_KEY }"),
    ("statement", "expressionstmt | compoundstmt | selectionstmt | iterationstmt | returnstmt"),
    ("expressionstmt", "[expression] PUNCTUATION_OPERATOR"),
    ("selectionstmt", "CONTROL_TYPE_KEY PUNCTUATION_OPERATOR expression PUNCTUATION_OPERATOR statement | CONTROL_TYPE_KEY PUNCTUATION_OPERATOR expression PUNCTUATION_OPERATOR statement CONTROL_TYPE_KEY  statement"),
    ("iterationstmt", "CONTROL_TYPE_KEY PUNCTUATION_OPERATOR expression PUNCTUATION_OPERATOR statement"),
    ("returnstmt", "FUNCTION_TYPE_KEY [ expression ] PUNCTUATION_OPERATOR"),
    ("expression", "var ASSIGNMENT_OPERATOR expression | simpleexpression"),
    ("var", "IDENTIFIER | IDENTIFIER PUNCTUATION_OPERATOR expression PUNCTUATION_OPERATOR"),
    ("simpleexpression", "additiveexpression [ relop additiveexpression ]"),
    ("relop", "RELATIONAL_OPERATOR"),
    ("additiveexpression", "term {ARITHMETIC_OPERATOR}")  ,
    ("addop", "ARITHMETIC_OPERATOR"),
    ("term", "factor {ARITHMETIC_OPERATOR}")  ,
    ("mulop", "ARITHMETIC_OPERATOR"),
    ("factor", "PUNCTUATION_OPERATOR expression PUNCTUATION_OPERATOR | var | call | NUMBER"),
    ("call", "IDENTIFIER PUNCTUATION_OPERATOR args PUNCTUATION_OPERATOR"),
    ("args", "[ arglist ]"),
    ("arglist", "expression {PUNCTUATION_OPERATOR expression}")  
]